### ISSUE TITLE
Cannot use `motion_require` in my projects

### ISSUE THREAD

**Issue by DougPuchalski** [clayallsopp/motion-require#12]
Whenever I add `motion_require` to a file, the compile bombs with:

```
undefined method `motion_require' for main:TopLevel (NoMethodError)
```

Does that look familiar?

**Comment by clayallsopp** [comment]
What's you compile order look like? Is `detect_dependencies` enabled?

**Comment by DougPuchalski** [comment]
I'm trying to run `rake spec` on https://github.com/aceofspades/MotionModel/tree/motion_require. Requiring motion-support pretty early, and detect_dependencies is false.

Results:

```
2013-05-06 11:24:18.215 MotionModel[45617:c07] undefined method `motion_require' for main:TopLevel (NoMethodError)
2013-05-06 11:24:18.217 MotionModel[45617:c07] *** Terminating app due to uncaught exception 'NoMethodError', reason: 'undefined method `motion_require' for main:TopLevel (NoMethodError)
'
*** First throw call stack:
(0x1ea6012 0x816e7e 0x3a2dc4 0xae95 0x9cdd)
libc++abi.dylib: terminate called throwing an exception
```

**Comment by clayallsopp** [comment]
Right, but exactly how early/is `ext.rb` in the compile order? Does it come before all of the files using `motion_require`?

**Comment by clayallsopp** [comment]
Yeah I checked the repo out and motion-require's `ext.rb` is getting required pretty late:

```
Compile /Users/clayallsopp/Projects/Motion/MotionModel/motion/adapters/sql/sqlite3_adapter.rr
/Users/clayallsopp/Projects/Motion/MotionModel/motion/adapters/sql/sql_db_adapter.rb
........
/Users/clayallsopp/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/motion-require-0.0.6/motion/ext.rb
```

this is probably because it's also using motion-support, and motion-require hasn't been tested when being used with multiple libraries. I'll work on it now.

**Comment by DougPuchalski** [comment]
I got some help from @tkadauke moments ago and pushed to this branch. It's now passing. He made some mods that I did not expect, I'm going to try that in my app now too. Maybe just have a look and :thumbsup: or :thumbsdown: what he's done?

Thanks for the help!

**Comment by clayallsopp** [comment]
Ohhhh I see, yeah that's all good.

**Comment by DougPuchalski** [comment]
Is some of that missing in your README?

**Comment by clayallsopp** [comment]
Good call, I added a small note about it: 455cb6f25b5c8ba3edb05fc79fdfc189e944efc9

As the commit notes, motion-require is sort of an all-or-nothing thing at this point, so using it in conjunction with the traditional `app.files <<` workflow could mess things up.
