### ISSUE TITLE
ext.rb not necessary anymore?

### ISSUE THREAD

**Issue by jamonholmgren** [clayallsopp/motion-require#14]
Since https://github.com/HipByte/RubyMotion/pull/82 has been merged, does this mean that ext.rb is no longer necessary?

https://github.com/clayallsopp/motion-require/blob/master/lib/motion-require/ext.rb#L1

**Comment by clayallsopp** [comment]
Good call, thanks! I've also removed it from BubbleWrap: https://github.com/rubymotion/BubbleWrap/commit/508f965fcc7f5d25e3ebf2e1f03b18d7a65e63ec
